const PRODUCT_SERVICE_URL =
  process.env.NEXT_PUBLIC_PRODUCT_SERVICE_URL || "http://localhost:4002";
const USER_SERVICE_URL =
  process.env.NEXT_PUBLIC_USER_SERVICE_URL || "http://localhost:4001";
const MODERATION_SERVICE_URL =
  process.env.NEXT_PUBLIC_MODERATION_SERVICE_URL || "http://localhost:4003";
const CART_SERVICE_URL =
  process.env.NEXT_PUBLIC_CART_SERVICE_URL || "http://localhost:4004";
const REPORT_SERVICE_URL =
  process.env.NEXT_PUBLIC_REPORT_SERVICE_URL || "http://localhost:4005";
const PAYMENT_SERVICE_URL =
  process.env.NEXT_PUBLIC_PAYMENT_SERVICE_URL || "http://localhost:4008";

export {
  PRODUCT_SERVICE_URL,
  USER_SERVICE_URL,
  MODERATION_SERVICE_URL,
  CART_SERVICE_URL,
  REPORT_SERVICE_URL,
  PAYMENT_SERVICE_URL,
};
